### ISSUE TITLE
error

### ISSUE THREAD

**Issue by expressups** [Ibonok/elastic_scan#2]
C:\Users\Administrator\elastic_scan-master>elastic_scan.py --ip 8.8.8.8:
9200
##################################################
        Connection Timeout: 30
        Connection Retries: False
        Scroll Size: 1
        Indexes: *
        Dump Elasticsearch Host: False
        Output Format: None
##################################################
Connect to  8.8.8.8:9200
Traceback (most recent call last):
  File "C:\Users\Administrator\elastic_scan-master\elastic_scan.py", line 305, i
n <module>
    single_ip(value)
  File "C:\Users\Administrator\elastic_scan-master\elastic_scan.py", line 245, i
n single_ip
    es = create_connection(ip)
  File "C:\Users\Administrator\elastic_scan-master\elastic_scan.py", line 236, i
n create_connection
    print (Fore.BLUE + 'Name: ' + version['name'] + '\nClustername: ' + version[
'cluster_name'] + '\nLucene Version: ' + version['version']['lucene_version'])
KeyError: 'cluster_name'

**Comment by Ibonok** [comment]
Hi, which Python version do you use? If i try to connect to 8.8.8.8:9200 (Google DNS, Port is unreachable) i got following Error:

```
Error: Connection Timeout
Error go next
```
I think this is a Version issue. 

Regards,

Ibonok
