### ISSUE TITLE
Error to run "python3 elastic_scan.py --help"

### ISSUE THREAD

**Issue by GabrielMioranza** [Ibonok/elastic_scan#3]
![image](https://user-images.githubusercontent.com/7417152/59545890-c7b56480-8efb-11e9-9194-a55a0eb05b6e.png)

How i can resolve this?

**Comment by GabrielMioranza** [comment]
Using WSL Kali Linux, i have to install all modules separated using pip,.
By default, the pip aren't installed and you have to do before.

"sudo apt-get install python-pip"

**Comment by TheSidd** [comment]
I am getting this same error on Kali. Attached image has python and pip versions too. 

![image](https://user-images.githubusercontent.com/16534440/76242701-24f8ff00-625d-11ea-8289-f0f8c8a53509.png)
