### ISSUE TITLE
Yara library name is out of date

### ISSUE THREAD

**Issue by 0xpan1c** [Ibonok/elastic_scan#4]
This was an easy fix but one worth noting:

`root@kali:/opt/elastic_scan# pip3 install python-yara
Collecting python-yara
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/python-yara/`

The new URL is https://pypi.org/project/yara-python/ (note the new library name). Once I ran this, everything worked well.

`pip3 install yara-python`

Another way to correct this is just to update `requirements.txt` to include `yara-python==3.10.0`

**Comment by vforbox** [comment]
update `requirements.txt`:
`root@kali:~/elastic_scan# sed -i 's/python-yara/yara-python/' requirements.txt`

**Comment by GabrielMioranza** [comment]
i solved the problem just add a comment disabling the yara lib

**Comment by Ibonok** [comment]
@vforbox 
Thanks i change the requirements.txt
