### ISSUE TITLE
ImportError : No module named Elasticsearch

### ISSUE THREAD

**Issue by TheSidd** [Ibonok/elastic_scan#5]
I have installed pip3, python3 as well as requirements.txt but I get below error

![image](https://user-images.githubusercontent.com/16534440/76286553-899d7380-62c8-11ea-821a-97d8931a73b6.png)

If I try to install Elasticsearch I get error saying already exists.

**Comment by Ibonok** [comment]
I tested it on the following version of Kali and had no problem:

![Bildschirmfoto von 2020-03-10 15-31-14](https://user-images.githubusercontent.com/37837775/76322901-3df8c300-62e4-11ea-9a43-26383cc15aeb.png)

pip:

![Bildschirmfoto von 2020-03-10 15-36-12](https://user-images.githubusercontent.com/37837775/76323367-ea3aa980-62e4-11ea-95b8-59be4a5204f8.png)

executed:

![Bildschirmfoto von 2020-03-10 15-34-12](https://user-images.githubusercontent.com/37837775/76323216-b495c080-62e4-11ea-9a6c-d399e3c2323c.png)

Can you pls try: `python3 elastic_scan.py`

**Comment by TheSidd** [comment]
Same error :(

![image](https://user-images.githubusercontent.com/16534440/76329274-5da6e000-6312-11ea-9c78-1d1412b0d1b0.png)

**Comment by Ibonok** [comment]
Can you try:

`python3 elastic_scan.py` 

not 

`python elastic_scan.py`

**Comment by TheSidd** [comment]
Thanks that worked.
