### ISSUE TITLE
HTTPS elastic server support with invalid cert

### ISSUE THREAD

**Issue by jen140** [Ibonok/elastic_scan#6]
When accessing elastic instance on port 9200 that has https support the following error appears:
"Not an Elastic Search Instanz
Error go next"

When specifying https in the beginning:
python3 elastic_scan.py --ip https://IP:9200

I get the exception "urllib3.exceptions.SSLError: ("hostname 'IP' doesn't match 'DOMAIN'",)".

Looked through the documentation but PoolManager doesn't appear to accept "assert_hostname=False".

Thanks.

**Comment by Ibonok** [comment]
Hi jen140,

I have inserted a query that checks for TLS before. 
Can you please test it.

Regards,

**Comment by jen140** [comment]
Latest version still has the same issue:
"Not an Elastic Search Instanz
Error go next"

**Comment by Ibonok** [comment]
Oh let me check again.

**Comment by Ibonok** [comment]
I have implemented support for tls, with my test setup it works now without problems.
