### ISSUE TITLE
Dependencies issues with Debian 10

### ISSUE THREAD

**Issue by jen140** [Ibonok/elastic_scan#7]
Hello.

So when trying to install the latest version, the dependencies are not satisfied. Having the latest version of python3/pip installed when running:
pip3 install -r requirements.txt

ERROR: requests 2.20.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.8 which is incompatible.

**Comment by Ibonok** [comment]
I use Arch Linux and it works without problems. I can change the requirements.txt to the needed value. Or you can try it in a virtualenv.

**Comment by jen140** [comment]
It also works on CentOS 7 without any issue but if it's possible to downgrade it would be great =)

**Comment by Ibonok** [comment]
I change the req file to urllib3 1.24.2 due security issues
